### ISSUE TITLE
Fix YAML Indentation

### ISSUE THREAD

**Issue by hyoklee** [grc-iit/grc-iit.github.io#116]
https://grc.iit.edu/docs/iowarp/components/runtime/deploying-mods#build-a-pipeline-script

```
name: test_pipeline
env: chimaera
pkgs:
  - pkg_type: chimaera_run
    pkg_name: chimaera_run
    sleep: 5
    do_dbg: false
    dbg_port: 4000
    port: 6000
    modules: ['example_compressor']
 - pkg_type: compressor
   pkg_name: compressor
```
